# TCL File Generated by Component Editor 12.1sp1
# Sun Mar 21 12:15:46 MSK 2021
# DO NOT MODIFY


# 
# avalon_st_drainer "Avalon-ST Drainer" v1.0
# VBKesha 2021.03.21.12:15:46
# Avalon-ST Packet Drainer
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module avalon_st_drainer
# 
set_module_property DESCRIPTION "Avalon-ST Packet Drainer"
set_module_property NAME avalon_st_drainer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Bridges and Adapters/Streaming"
set_module_property AUTHOR VBKesha
set_module_property DISPLAY_NAME "Avalon-ST Drainer"
set_module_property TOP_LEVEL_HDL_FILE avalon_st_drainer.v
set_module_property TOP_LEVEL_HDL_MODULE avalon_st_drainer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME avalon_st_drainer
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file avalon_st_drainer.v {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true

add_interface_port reset_sink reset reset_n Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in associatedReset reset_sink
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true

add_interface_port in in_valid valid Input 1
add_interface_port in in_sof startofpacket Input 1
add_interface_port in in_eof endofpacket Input 1
add_interface_port in in_data data Input 32
add_interface_port in in_empty empty Input 2
add_interface_port in in_ready ready Output 1

# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset_sink
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true

add_interface_port out out_valid valid Output 1
add_interface_port out out_sof startofpacket Output 1
add_interface_port out out_eof endofpacket Output 1
add_interface_port out out_data data Output 32
add_interface_port out out_empty empty Output 2
add_interface_port out out_ready ready Input 1


# 
# connection point control
# 
add_interface control conduit end
set_interface_property control associatedClock clock
set_interface_property control associatedReset ""
set_interface_property control ENABLED true

add_interface_port control drain export Input 1

