# TCL File Generated by Component Editor 12.1sp1
# Sun Apr 18 11:19:23 MSD 2021
# DO NOT MODIFY


# 
# CXD2545S_SUBQ "CXD2545S_SUBQ" v1.4
# null 2021.04.18.11:19:23
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module CXD2545S_SUBQ
# 
set_module_property NAME CXD2545S_SUBQ
set_module_property VERSION 1.4
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Interfaces
set_module_property DISPLAY_NAME CXD2545S_SUBQ
set_module_property TOP_LEVEL_HDL_FILE CXD2545S_SUBQ.v
set_module_property TOP_LEVEL_HDL_MODULE CXD2545S_SUBQ
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME CXD2545S_SUBQ
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file CXD2545S_SUBQ.v {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point SUBQ_OUT
# 
add_interface SUBQ_OUT conduit end
set_interface_property SUBQ_OUT associatedClock ""
set_interface_property SUBQ_OUT associatedReset ""
set_interface_property SUBQ_OUT ENABLED true

add_interface_port SUBQ_OUT in_sqck export Input 1
add_interface_port SUBQ_OUT out_scor export Output 1
add_interface_port SUBQ_OUT out_sqso export Output 1
add_interface_port SUBQ_OUT out_emph export Output 1


# 
# connection point SUBQ_Sink
# 
add_interface SUBQ_Sink avalon_streaming end
set_interface_property SUBQ_Sink associatedClock Clock
set_interface_property SUBQ_Sink dataBitsPerSymbol 8
set_interface_property SUBQ_Sink errorDescriptor ""
set_interface_property SUBQ_Sink firstSymbolInHighOrderBits true
set_interface_property SUBQ_Sink maxChannel 0
set_interface_property SUBQ_Sink readyLatency 0
set_interface_property SUBQ_Sink ENABLED true

add_interface_port SUBQ_Sink in_eof endofpacket Input 1
add_interface_port SUBQ_Sink in_sof startofpacket Input 1
add_interface_port SUBQ_Sink out_ready ready Output 1
add_interface_port SUBQ_Sink in_valid valid Input 1
add_interface_port SUBQ_Sink in_data data Input 32
add_interface_port SUBQ_Sink in_empty empty Input 2


# 
# connection point Clock
# 
add_interface Clock clock end
set_interface_property Clock clockRate 0
set_interface_property Clock ENABLED true

add_interface_port Clock clk clk Input 1


# 
# connection point Reset
# 
add_interface Reset reset end
set_interface_property Reset associatedClock Clock
set_interface_property Reset synchronousEdges DEASSERT
set_interface_property Reset ENABLED true

add_interface_port Reset reset reset Input 1

