# TCL File Generated by Component Editor 12.1sp1
# Thu Mar 04 01:31:12 MSK 2021
# DO NOT MODIFY


# 
# CXD2545_CPU "CXD2545_CPU" v1.0
# VBKesha 2021.03.04.01:31:12
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module CXD2545_CPU
# 
set_module_property NAME CXD2545_CPU
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Interfaces
set_module_property AUTHOR VBKesha
set_module_property DISPLAY_NAME CXD2545_CPU
set_module_property TOP_LEVEL_HDL_FILE CXD2545_CPU.v
set_module_property TOP_LEVEL_HDL_MODULE CXD2545_CPU
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME CXD2545_CPU
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file CXD2545_CPU.v {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges BOTH
set_interface_property clock_reset ENABLED true

add_interface_port clock_reset rst_n reset Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset clock_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave m_addr address Input 4
add_interface_port avalon_slave m_read_data readdata Output 32
add_interface_port avalon_slave m_read read_n Input 1
add_interface_port avalon_slave m_write_data writedata Input 32
add_interface_port avalon_slave m_write write_n Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint avalon_slave
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset clock_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender m_irq irq_n Output 1


# 
# connection point cxd_cpu
# 
add_interface cxd_cpu conduit end
set_interface_property cxd_cpu associatedClock ""
set_interface_property cxd_cpu associatedReset ""
set_interface_property cxd_cpu ENABLED true

add_interface_port cxd_cpu CLOK export Input 1
add_interface_port cxd_cpu DATA export Input 1
add_interface_port cxd_cpu XLAT export Input 1

