# TCL File Generated by Component Editor 12.1sp1
# Wed Jan 30 20:32:07 GMT+03:00 2019
# DO NOT MODIFY


# 
# CXD2545_DATAOUT "CXD2545_DATAOUT" v1.0
# VBKesha 2019.01.30.20:32:07
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module CXD2545_DATAOUT
# 
set_module_property NAME CXD2545_DATAOUT
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Interfaces
set_module_property AUTHOR VBKesha
set_module_property DISPLAY_NAME CXD2545_DATAOUT
set_module_property TOP_LEVEL_HDL_FILE CXD2545_DATAOUT.v
set_module_property TOP_LEVEL_HDL_MODULE CXD2545_DATAOUT
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME CXD2545_DATAOUT
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file CXD2545_DATAOUT.v {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 
add_parameter DIV_REG STD_LOGIC_VECTOR 0
set_parameter_property DIV_REG DEFAULT_VALUE 0
set_parameter_property DIV_REG DISPLAY_NAME DIV_REG
set_parameter_property DIV_REG TYPE STD_LOGIC_VECTOR
set_parameter_property DIV_REG UNITS None
set_parameter_property DIV_REG ALLOWED_RANGES 0:31
set_parameter_property DIV_REG HDL_PARAMETER true
add_parameter FIFO_REG STD_LOGIC_VECTOR 1
set_parameter_property FIFO_REG DEFAULT_VALUE 1
set_parameter_property FIFO_REG DISPLAY_NAME FIFO_REG
set_parameter_property FIFO_REG TYPE STD_LOGIC_VECTOR
set_parameter_property FIFO_REG UNITS None
set_parameter_property FIFO_REG ALLOWED_RANGES 0:31
set_parameter_property FIFO_REG HDL_PARAMETER true
add_parameter FIFO_READ STD_LOGIC_VECTOR 2
set_parameter_property FIFO_READ DEFAULT_VALUE 2
set_parameter_property FIFO_READ DISPLAY_NAME FIFO_READ
set_parameter_property FIFO_READ TYPE STD_LOGIC_VECTOR
set_parameter_property FIFO_READ UNITS None
set_parameter_property FIFO_READ ALLOWED_RANGES 0:31
set_parameter_property FIFO_READ HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true

add_interface_port clock_sink clk clk Input 1


# 
# connection point clock_sink_reset
# 
add_interface clock_sink_reset reset end
set_interface_property clock_sink_reset associatedClock clock_sink
set_interface_property clock_sink_reset synchronousEdges DEASSERT
set_interface_property clock_sink_reset ENABLED true

add_interface_port clock_sink_reset rst_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressAlignment DYNAMIC
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock_sink
set_interface_property avalon_slave associatedReset clock_sink_reset
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave isMemoryDevice false
set_interface_property avalon_slave isNonVolatileStorage false
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave printableDevice false
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave addr address Input 4
add_interface_port avalon_slave read_data readdata Output 32
add_interface_port avalon_slave write_data writedata Input 32
add_interface_port avalon_slave read_n read_n Input 1
add_interface_port avalon_slave write_n write_n Input 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point CXD_DATA
# 
add_interface CXD_DATA conduit end
set_interface_property CXD_DATA associatedClock ""
set_interface_property CXD_DATA associatedReset ""
set_interface_property CXD_DATA ENABLED true

add_interface_port CXD_DATA emph export Output 1
add_interface_port CXD_DATA c2po export Output 1
add_interface_port CXD_DATA lrck export Input 1
add_interface_port CXD_DATA cddat export Output 1
add_interface_port CXD_DATA cdlbit export Input 1
add_interface_port CXD_DATA cdclk export Input 1


# 
# connection point CXD_SUBQ
# 
add_interface CXD_SUBQ conduit end
set_interface_property CXD_SUBQ associatedClock ""
set_interface_property CXD_SUBQ associatedReset ""
set_interface_property CXD_SUBQ ENABLED true

add_interface_port CXD_SUBQ scor export Output 1
add_interface_port CXD_SUBQ sqck export Input 1
add_interface_port CXD_SUBQ sqso export Output 1


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avalon_slave
set_interface_property irq associatedClock clock_sink
set_interface_property irq associatedReset clock_sink_reset
set_interface_property irq ENABLED true

add_interface_port irq irq_n irq_n Output 1

