# TCL File Generated by Component Editor 12.1sp1
# Fri Mar 19 19:44:59 MSK 2021
# DO NOT MODIFY


# 
# CXD2545S_OUT "CXD2545S_OUT" v1.8
# VBKesha 2021.03.19.19:44:59
# 
# 

# 
# request TCL package from ACDS 11.0
# 
package require -exact sopc 11.0


# 
# module CXD2545S_OUT
# 
set_module_property NAME CXD2545S_OUT
set_module_property VERSION 1.8
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Interfaces
set_module_property AUTHOR VBKesha
set_module_property DISPLAY_NAME CXD2545S_OUT
set_module_property TOP_LEVEL_HDL_FILE CXD2545S_OUT.v
set_module_property TOP_LEVEL_HDL_MODULE CXD2545S_OUT
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property STATIC_TOP_LEVEL_MODULE_NAME CXD2545S_OUT
set_module_property FIX_110_VIP_PATH false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# files
# 
add_file CXD2545S_OUT.v {SYNTHESIS SIMULATION}


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true

add_interface_port clock_reset rst reset_n Input 1


# 
# connection point data_in
# 
add_interface data_in avalon_streaming end
set_interface_property data_in associatedClock clock
set_interface_property data_in associatedReset clock_reset
set_interface_property data_in dataBitsPerSymbol 8
set_interface_property data_in errorDescriptor ""
set_interface_property data_in firstSymbolInHighOrderBits true
set_interface_property data_in maxChannel 0
set_interface_property data_in readyLatency 0
set_interface_property data_in ENABLED true

add_interface_port data_in in_valid valid Input 1
add_interface_port data_in in_data data Input 32
add_interface_port data_in in_eof endofpacket Input 1
add_interface_port data_in in_sof startofpacket Input 1
add_interface_port data_in in_ready ready Output 1
add_interface_port data_in in_empty empty Input 2


# 
# connection point cd_data_bus
# 
add_interface cd_data_bus conduit end
set_interface_property cd_data_bus associatedClock ""
set_interface_property cd_data_bus associatedReset ""
set_interface_property cd_data_bus ENABLED true

add_interface_port cd_data_bus cd_clk export Output 1
add_interface_port cd_data_bus cd_lr export Output 1
add_interface_port cd_data_bus cd_data export Output 1
add_interface_port cd_data_bus cd_c2po export Output 1

